### ISSUE TITLE
Memasukkan Id yang sama masih bisa masuk 

### ISSUE THREAD

**Issue by Windaka** [nandanugg/LearnRESTMiddlewareSiang#1]
![image](https://user-images.githubusercontent.com/60391523/107001216-d8df7300-67bb-11eb-9533-2152dd935936.png)

@nandanugg 
Step getting bugs: 
a. 
b. 
c.

**Comment by nandanugg** [comment]
Sebenarmba ini sedang diperbaiki dulu besk

**Comment by nandanugg** [comment]
Ini sudah diperbaiki di [disini](https://github.com/nandanugg/LearnRESTMiddlewareSiang/commit/c9a530465f67c35a93d215f9683f5b77dd94b964)

@nandanugg

**Comment by nandanugg** [comment]
LGTM
